source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'MKNetworkKit', '~> 0.87'
pod 'SDWebImage', '~> 3.7.1'
pod 'SVProgressHUD', '~> 1.0'
pod 'IQKeyboardManager', '~> 3.2.0'
pod 'RDVTabBarController', '~> 1.1.6'
pod 'RMDateSelectionViewController', '~> 1.4.3'
pod 'NYSegmentedControl', '~> 1.0.3'
pod 'AXRatingView', '~> 1.0.3'
